version: 2
project_name: vpd
before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
builds:
  - binary: vpd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: "{{ .ProjectName }}"
    repository:
      owner: VojtechPastyrik
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/VojtechPastyrik/vpd"
    description: "Vojtech Pastyrik Utils"
    license: "MIT"
    install: |
      bin.install "vpd"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

dockers_v2:
  - id: vpd
    dockerfile: Dockerfile.goreleaser
    ids:
      - vpd
    images:
      - "vojtechpastyrik/vpd"
      - "ghcr.io/vojtechpastyrik/vpd"
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/VojtechPastyrik/vpd"
      "org.label-schema.schema-version": "1.0"
      "org.label-schema.version": "{{.Version}}"
      "org.label-schema.name": "{{.ProjectName}}"
      "com.github.actions.name": "{{.ProjectName}}"
      "repository": "https://github.com/VojtechPastyrik/vpd"
      "maintainer": "Vojtech Pastyrik <vojtech@pastyrik.dev>"


changelog:
  filters:
    exclude:
      - '^VERSION'

nfpms:
  - id: vpd-deb
    package_name: vpd
    formats:
      - deb
    maintainer: "Vojtech Pastyrik <vojtech@pastyrik.dev>"
    description: "Vojtech Pastyrik Utils"
    homepage: "https://github.com/VojtechPastyrik/vpd"
    license: "MIT"
    vendor: "Vojtech Pastyrik"
    section: "utils"
    priority: "optional"
    conflicts:
      - vpd-old
    replaces:
      - vpd-old
    provides:
      - vpd
    dependencies:
      - libc6
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}.deb"
    bindir: /usr/bin
  - id: vpd-rpm
    package_name: vpd
    formats:
      - rpm
    maintainer: "Vojtech Pastyrik <vojtech@pastyrik.dev>"
    description: "Vojtech Pastyrik Utils"
    homepage: "https://github.com/VojtechPastyrik/vpd"
    license: "MIT"
    vendor: "Vojtech Pastyrik"
    section: "utils"
    priority: "optional"
    conflicts:
      - vpd-old
    replaces:
      - vpd-old
    provides:
      - vpd
    dependencies:
      - libc6
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}.rpm"
    bindir: /usr/bin