package cmd

import (
	_ "github.com/VojtechPastyrik/vpd/cmd/api"
	_ "github.com/VojtechPastyrik/vpd/cmd/api/load"
	_ "github.com/VojtechPastyrik/vpd/cmd/azure"
	_ "github.com/VojtechPastyrik/vpd/cmd/azure/subscription"
	_ "github.com/VojtechPastyrik/vpd/cmd/base64"
	_ "github.com/VojtechPastyrik/vpd/cmd/base64/interactive_clipboard"
	_ "github.com/VojtechPastyrik/vpd/cmd/cpu"
	_ "github.com/VojtechPastyrik/vpd/cmd/cpu/benchmark"
	_ "github.com/VojtechPastyrik/vpd/cmd/cpu/info"
	_ "github.com/VojtechPastyrik/vpd/cmd/cpu/load"
	_ "github.com/VojtechPastyrik/vpd/cmd/cpu/stress"
	_ "github.com/VojtechPastyrik/vpd/cmd/generate_docs"
	_ "github.com/VojtechPastyrik/vpd/cmd/git"
	_ "github.com/VojtechPastyrik/vpd/cmd/git/clean_branches"
	_ "github.com/VojtechPastyrik/vpd/cmd/git/reauthor_commit"
	_ "github.com/VojtechPastyrik/vpd/cmd/http_test_server"
	_ "github.com/VojtechPastyrik/vpd/cmd/ip"
	_ "github.com/VojtechPastyrik/vpd/cmd/jwt"
	_ "github.com/VojtechPastyrik/vpd/cmd/jwt/parse"
	_ "github.com/VojtechPastyrik/vpd/cmd/k8s"
	_ "github.com/VojtechPastyrik/vpd/cmd/k8s/add_context"
	_ "github.com/VojtechPastyrik/vpd/cmd/k8s/ingress"
	_ "github.com/VojtechPastyrik/vpd/cmd/k8s/remove_context"
	_ "github.com/VojtechPastyrik/vpd/cmd/memory"
	_ "github.com/VojtechPastyrik/vpd/cmd/memory/allocpatterns"
	_ "github.com/VojtechPastyrik/vpd/cmd/memory/info"
	_ "github.com/VojtechPastyrik/vpd/cmd/memory/leaktest"
	_ "github.com/VojtechPastyrik/vpd/cmd/memory/load"
	_ "github.com/VojtechPastyrik/vpd/cmd/mock_http_server"
	_ "github.com/VojtechPastyrik/vpd/cmd/rabbitmq"
	_ "github.com/VojtechPastyrik/vpd/cmd/rabbitmq/function"
	_ "github.com/VojtechPastyrik/vpd/cmd/rabbitmq/load"
	_ "github.com/VojtechPastyrik/vpd/cmd/rabbitmq/put_message"
	_ "github.com/VojtechPastyrik/vpd/cmd/rabbitmq/read_queue"
	_ "github.com/VojtechPastyrik/vpd/cmd/release"
	"github.com/VojtechPastyrik/vpd/cmd/root"
	_ "github.com/VojtechPastyrik/vpd/cmd/tls"
	_ "github.com/VojtechPastyrik/vpd/cmd/tls/generate_cert"
	_ "github.com/VojtechPastyrik/vpd/cmd/tls/parse"
	_ "github.com/VojtechPastyrik/vpd/cmd/tls/parse_file"
	_ "github.com/VojtechPastyrik/vpd/cmd/vault"
	_ "github.com/VojtechPastyrik/vpd/cmd/vault/init_unseal"
	_ "github.com/VojtechPastyrik/vpd/cmd/vaultino"
	_ "github.com/VojtechPastyrik/vpd/cmd/vaultino/create"
	_ "github.com/VojtechPastyrik/vpd/cmd/vaultino/decrypt"
	_ "github.com/VojtechPastyrik/vpd/cmd/vaultino/edit"
	_ "github.com/VojtechPastyrik/vpd/cmd/vaultino/get"
	_ "github.com/VojtechPastyrik/vpd/cmd/youtrack"
	_ "github.com/VojtechPastyrik/vpd/cmd/youtrack/track_time"
	"github.com/spf13/cobra"
)

func Execute() {
	cobra.CheckErr(root.RootCmd.Execute())
}
